apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: proxmox-vm-provisioner-v2
  namespace: flux-system
spec:
  interval: 5m

  # tfコードを取ってくる先（すでにある GitRepository）
  sourceRef:
    kind: GitRepository
    name: my-infra-repo
    namespace: flux-system

  # リポジトリ内の tf ファイルがある場所に合わせる
  path: ./terraform/proxmox-vms

  # 自動 approve したい場合（まずは auto でOK）
  approvePlan: auto

  # ロック関連は 0s だとトラブルになりやすいので少し待つ
  tfstate:
    lockTimeout: 5m

  upgradeOnInit: true
